'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var NOTIFICATION_CUSTOMIZE = exports.NOTIFICATION_CUSTOMIZE = 'NOTIFICATION_CUSTOMIZE';
var NOTIFICATION_CLEAR_BY_KEY = exports.NOTIFICATION_CLEAR_BY_KEY = 'NOTIFICATION_CLEAR_BY_KEY';
var NOTIFICATION_CLEAR = exports.NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';