'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var NOTIFICATION_INFO = exports.NOTIFICATION_INFO = 'NOTIFICATION_INFO';
var NOTIFICATION_WARNING = exports.NOTIFICATION_WARNING = 'NOTIFICATION_WARNING';
var NOTIFICATION_ERROR = exports.NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
var NOTIFICATION_SUCCESS = exports.NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
var NOTIFICATION_CLEAR_BY_KEY = exports.NOTIFICATION_CLEAR_BY_KEY = 'NOTIFICATION_CLEAR_BY_KEY';
var NOTIFICATION_CLEAR = exports.NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';